# Это файл конфигурации для гема ar-octopus
# Нужен только если используются две взаимосвязанные системы (как спок и корк).

<%=
  file = File.join(Rails.root, "config", "database_settings.yml")
  IO.read(file) if File.exist?(file)
%>

octopus:
  environments:
    - development
    - staging
    - production
  development:
    spock:
      <<: *database_common
      <<: *panel_user_development
  staging:
    spock:
      <<: *database_common
      <<: *panel_user_staging
  production:
    spock:
      <<: *database_common
      <<: *panel_user_production
